version: "3"
services:
  ## backend
  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - ./data/:/var/lib/postgresql/data

  ## api
  web:
    container_name: web
    platform: linux/x86_64
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: docker-compose.env
    volumes:
      - ./server/:/usr/src/app
    environment:
      - RAILS_ENV=development
    depends_on:
      - "database"