version: "3"
services:
  ## backend
  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - ./psql/data:/var/lib/postgresql/data

  ## api
  web:
    container_name: web
    build: .
    env_file: docker-compose.env
    volumes:
      - ./:/usr/src/app
    environment:
      - RAILS_ENV=development
    depends_on:
      - "database"