version: "3"
services:
  ## backend
  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - ./psql/data:/var/lib/postgresql/data

  ## api
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "1000:3000"
    env_file: docker-compose.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - "database"
    environment:
      - RAILS_ENV=development