default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: <%= "#{ENV.fetch("PG_DB_PREFIX")}-development" %>
  pool: 5
  username: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  host: database
  port: 5432

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV.fetch("PG_DB_PREFIX")}-test" %>

#production:
#  <<: *default
#  database: <%= "#{ENV.fetch("PG_DB_PREFIX")}-production" %>
